server:
  port: 8080

spring:
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

property:
  test:
    name: property depth test
propertyTest: test
propertyTestList: a,b,c

fruit:
  color-name: color
  list:
    - name: banana
      color: yellow
    - name: apple
      color: red