server:
  port: 8080

#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
#  type-aliases-package: com.study.springboot.domain

server.error:
  include-exception: true
  include-stacktrace: ALWAYS # 오류 응답에 stacktrace 내용을 포함할 지 여부
#  path: '/error' # 오류 응답을 처리할 Handler의 경로
#  whitelabel.enabled: false # 서버 오류 발생시 브라우저에 보여줄 기본 페이지 생성 여부

spring:
  datasource:
    generate-unique-name: false # db를 testdb로 고정 (jdbc:h2:mem:testdb)
#    url: jdbc:mysql://127.0.0.1:3306/user17?serverTimezone=Asia/Seoul&useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false
#    username: spring
#    password: spring
#    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:h2:mem:mybatis-test
    username: sa
    password:
    hikari:
      maximum-pool-size: 4

  redis:
    host: localhost
    port: 6379

#spring:
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

property:
  test:
    name: property depth test
propertyTest: test
propertyTestList: a,b,c

fruit:
  color-name: color
  list:
    - name: banana
      color: yellow
    - name: apple
      color: red